# Generated by Django 2.2.13 on 2020-07-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0075_profile_last_frontend_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='hide_map',
            field=models.BooleanField(default=False, verbose_name='hide map'),
        ),
        migrations.AlterField(
            model_name='event',
            name='hide_attached_field_reports',
            field=models.BooleanField(default=False, verbose_name='hide field report numerical details?'),
        ),
    ]
